### ISSUE TITLE
H5 video cannot be played in Fullscreen，the fullscreen button is unclickable

### ISSUE THREAD

**Issue by lycstar** [fluttercommunity/flutter_webview_plugin#405] opened 2019-05-03 14:13 UTC
HTML video cannot be played in full screen,the full screen button is not clickable.

**Comment by lyzcw** [comment] 2019-05-21 08:40
Me too. It's a bad experience that the mobile  can't play video in full screen.

**Comment by charafau** [comment] 2019-06-11 11:09
Thank you for issue. It's a duplicate of https://github.com/fluttercommunity/flutter_webview_plugin/issues/423

**Closed by charafau** 2019-06-11 11:09 UTC
