### ISSUE TITLE
 break your Android build if it or its dependencies aren't compatible with AndroidX.

### ISSUE THREAD

**Issue by CatEatFishs** [fluttercommunity/flutter_webview_plugin#500] opened 2019-08-07 03:26 UTC
flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/hongka-liming/Downloads/flutter
    • Framework revision 7a4c33425d (3 months ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/hongka-liming/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ Brew can be used to install tools for iOS device development.
      Download brew at https://brew.sh/.

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • COR AL00 • 6EJ7N18526001222 • android-arm64 • Android 9 (API 28)

when I runing  flutter build apk  ,androdi studio will prompt an error

WARNING: This version of flutter_webview_plugin will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
How to solve it？

**Comment by LaurentiuSimionescu** [comment] 2019-09-11 07:06
*********************************************************
WARNING: This version of flutter_webview_plugin will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

**Comment by LaurentiuSimionescu** [comment] 2019-09-11 07:13
I am having this issue also.

**Comment by charafau** [comment] 2019-09-14 01:21
this is not an issue, just intended behaviour. you need to migrate your project to androidx to use the plugin.

closing

**Closed by charafau** 2019-09-14 01:21 UTC

**Comment by webelegan** [comment] 2021-09-20 15:00
![error](https://user-images.githubusercontent.com/17093250/134024914-c849e697-3ea3-45ac-9f35-0f33eda81dea.png)

**Comment by Mashood97** [comment] 2021-09-29 18:37
I am facing the same issues, any update regarding this issue

**Comment by efraespada** [comment] 2021-10-05 19:20
Same problem here

**Comment by qualitattechs** [comment] 2021-11-25 19:05
> ![error](https://user-images.githubusercontent.com/17093250/134024914-c849e697-3ea3-45ac-9f35-0f33eda81dea.png)

@charafau please help, I have the same issue too          *********************************************************
WARNING: This version of flutter_webview_plugin will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* Where:
Script '/Users/aemam/development/sdks/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/aemam/development/sdks/flutter/bin/flutter'' finished with non-zero exit value 1

**Comment by charafau** [comment] 2021-11-26 22:18
@qualitattechs  you need to update your andrid project's dependencies to AndroidX
